version: "3.7"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.13.1
    ports:
      - "16686:16686"
    restart: on-failure
  app2:
    build: ./app2
    links:
      - jaeger
      - app1
    depends_on:
      - jaeger
      - app1
    ports:
      - "8087:8087"
    environment:
      JAEGER_AGENT_HOST: jaeger
      SERVICE_FORMATTER: app1
  app1:
    build: ./app1
    links:
      - jaeger
    depends_on:
      - jaeger
    ports:
      - "8086:8086"
    environment:
      JAEGER_AGENT_HOST: jaeger