hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8086

sentry:
  dsn: http://ea4f89d98446a50e221f8d0b25b500ea@172.21.21.10:9000/5
  # in-app-includes: java/cicd
  debug: true
  # exception-resolver-order: 1
  # traces-sample-rate: 1.0


spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/shop_restful
    # Username: root
    # password: 10112002
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://database-mysql-svc.mysql.svc.cluster.local:3306/shop_restful?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    # url: ${SPRING_DATASOURCE_URL:jdbc:mysql://103.143.207.71:31734/shop_restful?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    Username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:ABC10112002}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      org:
        hibernate:
          envers:
            default_schema = shop_restful


# http://7d0f7a82090d84db4510769b6798fc98@172.21.21.10:9000/organizations/sentry/issues/?project=1&referrer=sidebar&statsPeriod=14d

# http://172.21.21.10:9000/organizations/sentry/issues/?project=1&referrer=sidebar&statsPeriod=14d